import './components/header.js'
import './components/transfer.js'
import './components/swiper.js'
import './components/offcanvas.js'
import './components/modal.js'
import './components/accordion.js'
import './components/popper.js'